### PR TITLE
Update repo  to reflect upstream changes

### PR DESCRIPTION
**Pull request by tvdijen**
Update this repo:
- Start using namespaces for Twig
- Add basic test framework
- Shorthand arrays

### CODE REVIEW

**Comment by tvdijen** [comment]
I've been running tests with this and appears to be functioning fine.. Doesn't fix our build @ SimpleSAMLphp though

**Comment by jaimeperez** [comment]
@tvdijen, since there's no CI setup for this repo yet, I can't check myself if the build passes with this PR (other than checking out the branch and testing manually). If you confirm it works, then I'll just merge it 😄

**Comment by tvdijen** [comment]
Let's set up CI then ;) I'll create a new PR for that and will rebase this one after you merge the CI-PR.

**Comment by tvdijen** [comment]
Yeah, it worked fine when I ran some tests!
P.S.:  If you're merging this, perhaps it's the right time to move the repo to the simplesamlphp-namespace as discussed during the hackaton!

**Comment by jaimeperez** [comment]
Merged! Regarding the move, it's a bit more tricky, because we depend on this in SSP and other places, and then we need to update the package name with the new vendor. That might require some coordination and duplicate repos for a while...

**Comment by tvdijen** [comment]
@jaimeperez I noticed that Packagist has support for so-called 'virtual packages', that are basically referrals to other repositories. That would mean that in theory you could move to repository to the simplesamlphp-namespace and keep a 'virtual package' under 'jaimeperez/twig-configurable-i18n'..
As an example, Psalm now has 'psalm/psalm' redirecting to 'vimeo/psalm'.

**Comment by jaimeperez** [comment]
Ah, wonderful! I'll check it out and try to plan the change to avoid disruptions as much as possible...

**Pull request merged**
